server:
  port: 9007
spring:
  application:
    name: huahua-search
  data:
    elasticsearch:
      cluster-nodes: 192.168.136.129:9300
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    instance-id: huahua_search   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: 八维云计算
  company.name: www.bawei.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$