server: 
  port: 9003
spring: 
  application:  
    name: huahua-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.136.129:3306/tensquare_qa?useUnicode=true&amp;characterEncoding=UTF8&&useSSL=false
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    instance-id: huahua_qa   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: 八维云计算
  company.name: www.bawei.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
jwt:
  config:
    key: huahua_shequ
